=== JaimeSFC/lenguajes-de-marcas-ejemplos/2 XSD/Tarea 2 - Evaluable/agendaVersion6.xsd
<xs:schema attributeFormDefault="unqualified" 
elementFormDefault="qualified" 
xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="agenda" type="agendaType" />

	<!-- ALARMATYPE -->
	<!-- ? Componentes diaType -->
	<xs:simpleType name="t_dia">
		<xs:restriction base="xs:integer">
			<xs:pattern value="(0[1-9]|[12]\d|3[01])" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="t_mes">
		<xs:restriction base="xs:integer">
			<xs:pattern value="(0?[1-9]|1[0-2])" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="t_anyo">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[2022-2199]{4}" />
		</xs:restriction>
	</xs:simpleType>

	<!-- ! Declaro diaType -->
	<xs:complexType name="diaType">
		<xs:sequence>
			<xs:element name="dia" type="t_dia" maxOccurs="unbounded" />
			<xs:element name="mes" type="t_mes" maxOccurs="unbounded" />
			<xs:element name="anyo" type="t_anyo" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!-- ? Componentes de horaType -->
	<xs:simpleType name="t_hora">
		<xs:restriction base="xs:integer">
			<xs:pattern value="([0-1]?[0-9]|2[0-3])" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="t_minuto">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[0-5][0-9]" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="t_segundo">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[00-59]{2}" />
		</xs:restriction>
	</xs:simpleType>

	<!-- ! Declaro horaType -->
	<xs:complexType name="horaType">
		<xs:sequence>
			<xs:element name="hora" type="t_hora" minOccurs="1" maxOccurs="1" />
			<xs:element name="minuto" type="t_minuto" minOccurs="1" maxOccurs="1" />
			<xs:element name="segundo" type="t_segundo" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<!-- ! Declaro diahoraType -->
	<xs:complexType name="diaHoraType">
		<xs:sequence>
			<xs:element type="diaType" name="dia" maxOccurs="unbounded" />
			<xs:element type="horaType" name="hora" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!-- ! Declaro alarmaType -->
	<xs:complexType name="alarmaType">
		<xs:sequence>
			<xs:element type="diaHoraType" name="diaHora" minOccurs="1" maxOccurs="1" />
			<xs:element type="xs:string" name="asunto" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="prioridad" use="optional" />
		<xs:attribute type="xs:integer" name="tono" use="optional" />
	</xs:complexType>

	<!-- * FIN componentes alarmaType -->


	<!-- CORREOTYPE -->

	<!-- * INICIO componentes correoType -->
	<!-- ? Atributo correoType  -->
	<xs:simpleType name="t_EntradaoSalida">
		<xs:restriction base="xs:string">
			<xs:pattern value="Entrada|Salida" />
		</xs:restriction>
	</xs:simpleType>

	<!-- ? Componentes correoType -->
	<xs:simpleType name="email_address">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{2,64}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="texto_libre_asunto_correo">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:maxLength value="255" />
		</xs:restriction>
	</xs:simpleType>

	<!-- ? Atributo de imágenes -->
	<xs:simpleType name="extension_imagenes">
		<xs:restriction base="xs:string">
			<xs:pattern value=".xml|.xsd|.jpg|.png|.pdf|.pps|.gif" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="imagenesType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="extension_imagenes" name="extension" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<!-- ! Declaro correoType -->
	<xs:complexType name="correoType">
		<xs:sequence>
			<xs:element type="email_address" name="remitente" />
			<xs:element type="email_address" name="destinatario" maxOccurs="unbounded" minOccurs="1" />
			<xs:element type="texto_libre_asunto_correo" name="asunto" maxOccurs="unbounded" minOccurs="0" />
			<xs:element type="imagenesType" name="imagenes" maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
		<xs:attribute type="t_EntradaoSalida" name="EntradaoSalida" use="optional" />
	</xs:complexType>

	<!-- * FIN componentes correoType -->

	<!-- contactoTYPE -->

	<!-- * INICIO componentes contactoTYPE -->
	<!-- ? Atributo contactoType  -->
	<xs:simpleType name="tipo_idioma">
		<xs:restriction base="xs:string">
			<xs:enumeration value="es" />
			<xs:enumeration value="en" />
			<xs:enumeration value="fr" />
		</xs:restriction>
	</xs:simpleType>

	<!-- ? Componentes contactoType -->
	<xs:simpleType name="tipo_empresaSiNo">
		<xs:restriction base="xs:string">
			<xs:enumeration value="si" />
			<xs:enumeration value="no" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="t_telefono">
		<xs:restriction base="xs:string">
			<xs:pattern value="\(?\+[0-9]{1,3}\)? ?-?[0-9]{1,3} ?-?[0-9]{3,5} ?-?[0-9]{4}( ?-?[0-9]{3})? ?(\w{1,10}\s?\d{1,6})?" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="nombreType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="tipo_idioma" name="idioma" use="required" />
				<xs:attribute type="tipo_empresaSiNo" name="empresaSiNo" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<!-- ! Declaro contactoType -->
	<xs:complexType name="contactoType">
		<xs:sequence>
			<xs:element type="nombreType" name="nombre" />
			<xs:element type="t_telefono" name="telefono" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!-- ! Declaro descencientes directos de agenda -->
	<xs:complexType name="alarmasType">
		<xs:sequence>
			<xs:element type="alarmaType" name="alarma" maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="correosType">
		<xs:sequence>
			<xs:element type="correoType" name="correo" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="contactosType">
		<xs:sequence>
			<xs:element type="contactoType" name="contacto" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="agendaType">
		<xs:sequence>
			<xs:element type="alarmasType" name="alarmas" />
			<xs:element type="correosType" name="correos" />
			<xs:element type="contactosType" name="contactos" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== JaimeSFC/lenguajes-de-marcas-ejemplos/Tareas-DAM/Tarea 2 - Evaluable/agendaVersion6.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="agendaVersion6.xsd">

	<alarmas>
		<alarma prioridad="alta" tono="3">
			<diaHora>
				<dia>
					<dia>25</dia>
					<mes>12</mes>
					<anyo>2022</anyo>
				</dia>
				<hora>
					<hora>07</hora>
					<minuto>00</minuto>
					<segundo>00</segundo>
				</hora>
			</diaHora>
			<asunto>A levantarse</asunto>
		</alarma>

		<alarma prioridad="baja" tono="1">
			<diaHora>
				<dia>
					<dia>25</dia>
					<mes>12</mes>
					<anyo>2022</anyo>
				</dia>
				<hora>
					<hora>16</hora>
					<minuto>00</minuto>
					<segundo>00</segundo>
				</hora>
			</diaHora>
			<asunto>Se acabó la siesta</asunto>
		</alarma>
	</alarmas>

	<correos>
		<correo EntradaoSalida="Salida">
			<remitente>jaime@gmail.com</remitente>
			<destinatario>joseluis@educastur.es</destinatario>
			<asunto>Tareas pendientes</asunto>
			<imagenes extension=".xml">agenda.xml</imagenes>
			<imagenes extension=".xsd">agenda.xsd</imagenes>
		</correo>

		<correo EntradaoSalida="Salida">
			<remitente>jaime@gmail.com</remitente>
			<destinatario>felipe@gmail.com</destinatario>
			<destinatario>leticia@gmail.com</destinatario>
			<asunto>Gatitos monísimos</asunto>
			<imagenes extension=".pps">gatitos.pps</imagenes>
		</correo>

		<correo EntradaoSalida="Entrada">
			<remitente>joseluis@educastur.es</remitente>
			<destinatario>jaime@gmail.com</destinatario>
			<asunto>Calificación Jaime</asunto>
			<imagenes extension=".jpg">boletin-notas.jpg</imagenes>
		</correo>
	</correos>

	<contactos>
		<contacto>
			<nombre idioma="en" empresaSiNo="si">Tesla</nombre>
			<telefono>+1273000001</telefono>
		</contacto>

		<contacto>
			<nombre idioma="es" empresaSiNo="si">Jamones de Jabugo</nombre>
			<telefono>+34959128668</telefono>
			<telefono>+34959128669</telefono>
		</contacto>

		<contacto>
			<nombre idioma="fr" empresaSiNo="no">Robespierre</nombre>
			<telefono>+33455638987</telefono>
		</contacto>
	</contactos>

</agenda>
