=== JaimeSFC/lenguajes-de-marcas-ejemplos/unidad6/XSD/Tareas-DAM/Tarea 1 - Evaluable/05-recetas.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Duda: que diferencia hay entre poner la raiz del XML, en este caso "recetas" como ID o como primer elemento? -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" id="recetas">
  <xs:element name="recetas">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="receta">
                <xs:complexType mixed="true">
						<!-- Mixed=true  permite aÃ±adir contenido dentro de la etiqueta ascendente -->
            <xs:sequence>
            <!-- En "nombre-receta" no entiendo xq si pongo minOccurs 1 falla la validacion del XML -->
              <xs:element minOccurs="0" maxOccurs="unbounded" name="nombre-receta" type="xs:string"/>
                          <xs:element name="description" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
              <xs:element name="ingredients">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="ingredient" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="preparation">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="step" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="score">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="user-review" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            		<!-- Los atributos de la receta, si los pongo al inicio, tb falla la validacion, no se xq -->
						<xs:attribute name="dificultad" type="xs:string" use="required"/>
						<!-- Si se aplica un valor por defecto, use no puede ser requerido sino opcional -->
						<xs:attribute name="picture" type="xs:string" use="optional" default="receta.jpg"/>
						<xs:attribute name="autor" type="xs:string" use="required"/>
						<xs:attribute name="country" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JaimeSFC/lenguajes-de-marcas-ejemplos/unidad6/XSD/Tareas-DAM/Tarea 1 - Evaluable/05-recetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<recetas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="05-recetas.xsd">  
    
	<!-- Mi primer plato favorito -->
	<receta dificultad="Fácil" picture="wp-content/gazpacho.png" autor="Martín Berasategui" country="España">
	<nombre-receta>Gazpacho</nombre-receta>
				<description>La sopa del verano, súper sencilla de preparar y súper refrescante.</description>
		<ingredients>
			Para 2 personas
			<ingredient>1 Ajo</ingredient>
			<ingredient>Perejil fresco (un manojo)</ingredient>
			<ingredient>1 barra de pan</ingredient>
			<ingredient>2 tomates</ingredient>
			<ingredient>5 pepinos</ingredient>
		</ingredients>
		<preparation>
			30 minutos
			<step>Pelar y cortar bien los vegetales, meter en la turmix con los demás ingredients.</step>
			<step>Tras 10 nminutos a potencia máxima, añadir 1 litro de agua y enfriar en la nevera.</step>
			<step>Dejar enfriar durante 20 minutos, pasado ese tiempo, ¡a disfrutar!</step>
		</preparation>
		<score>
			¡De rechupete!
			<user-review>Los usuarios han valorado con 5 estrellas esta receta</user-review>
		</score>
	</receta>

	<!-- Mi plato principal de la infancia -->
	<receta dificultad="Media" picture="wp-content/albondigas.png" autor="Jaimelon" country="España">
		Albóndigas tope la gama
		<description>La comida favorita de muchos niños,ricas ricas.</description>
		<ingredients>
			Para 6 personas
			<ingredient>500 gramos de carne picada de ternera</ingredient>
			<ingredient>Perejil</ingredient>
			<ingredient>Pan rallado</ingredient>
			<ingredient>1 diente de ajo</ingredient>
			<ingredient>1 cebolla dulce</ingredient>
		</ingredients>
		<preparation>
			40 minutos
			<step>1. Dorar la cebolla y el ajo, añadir la carne picada y freir a fuego medio brevemente, durante 3 minutos.</step>
			<step>2. Retirar la carne y dejar templar. Darle forma redonda a la carne con el pan rallado, haciendo bolitas.</step>
			<step>3. Freir las bolitas a fuego fuerte durante 10 minutos</step>
			<step>4. Añadir patatas fritas al gusto o guisantes de lata como guarnición</step>
		</preparation>
		<score>
			¡Para repetir!
			<user-review>Los usuarios han valorado con 4,2 estrellas esta receta</user-review>
		</score>
	</receta>

	<!-- El postre de los niños buenos -->
	<receta dificultad="Fácil" picture="wp-content/polos-de-coca-cola.png" autor="Pepe" country="España">
		Polos de coca cola
		<description>Un postre para hacer en familia. Es necesario contar con una polera.</description>
		<ingredients>
			Para 3 personas
			<ingredient>1 botella de coca cola de 2 litros</ingredient>
		</ingredients>
		<preparation>
			¡5 minutos!
			<step>1. Verter la coca cola en los espacios de la polera.</step>
			<step>2. Meter en el congelador durante 4 horas al menos.</step>
			<step>3. Pasado ese tiempo, la coca cola se habrá congelado... ¡y ya podremos disfrutar de nuestros polos de coca cola!</step>
		</preparation>
		<score>
			¡Chupao!
			<user-review>Los usuarios han valorado con 3,9 estrellas esta receta</user-review>
		</score>
	</receta>

</recetas>
