=== JaimeSFC/lenguajes-de-marcas-ejemplos/unidad6/XSD/Tareas-DAM/Tarea 1 - Evaluable/07-recetas.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" id="recetas">

	<!-- Definición de tipos de elementos y atributos -->

	<xs:simpleType name="tipo_integer_positivo">
		<xs:restriction base="xs:positiveInteger"/>
	</xs:simpleType>

	<xs:simpleType name="tipo_byte">
		<xs:restriction base="xs:byte"/>
	</xs:simpleType>

	<xs:simpleType name="tipo_texto_varchar">
		<xs:restriction base="xs:string">
			<xs:minLength value="0" />
			<xs:maxLength value="255" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipo_dia">
		<xs:restriction base="xs:integer">
			<xs:pattern value="(0[1-9]|[12]\d|3[01])" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipo_mes">
		<xs:restriction base="xs:string">
			<xs:pattern value="Enero|Febrero|Marzo|Abril|Mayo|Junio|Julio|Agosto|Septiembre|Octubre|Noviembre|Diciembre" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipo_anyo">
		<xs:restriction base="xs:short">
			<xs:pattern value="[2020-2199]{4}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipo_email">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{2,64}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipo_tiempo">
		<xs:restriction base="xs:integer">
			<xs:pattern value=" /^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$/" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipo_dificultad">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Fácil" />
			<xs:enumeration value="Media" />
			<xs:enumeration value="Difícil" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipo_pais">
		<xs:restriction base="xs:string">
			<xs:pattern value="^(AF|AX|AL|DZ|AS|AD|AO|AI|AQ|AG|AR|AM|AW|AU|AT|AZ|BS|BH|BD|BB|BY|BE|BZ|BJ|BM|BT|BO|BQ|BA|BW|BV|BR|IO|BN|BG|BF|BI|KH|CM|CA|CV|KY|CF|TD|CL|CN|CX|CC|CO|KM|CG|CD|CK|CR|CI|HR|CU|CW|CY|CZ|DK|DJ|DM|DO|EC|EG|SV|GQ|ER|EE|ET|FK|FO|FJ|FI|FR|GF|PF|TF|GA|GM|GE|DE|GH|GI|GR|GL|GD|GP|GU|GT|GG|GN|GW|GY|HT|HM|VA|HN|HK|HU|IS|IN|ID|IR|IQ|IE|IM|IL|IT|JM|JP|JE|JO|KZ|KE|KI|KP|KR|KW|KG|LA|LV|LB|LS|LR|LY|LI|LT|LU|MO|MK|MG|MW|MY|MV|ML|MT|MH|MQ|MR|MU|YT|MX|FM|MD|MC|MN|ME|MS|MA|MZ|MM|NA|NR|NP|NL|NC|NZ|NI|NE|NG|NU|NF|MP|NO|OM|PK|PW|PS|PA|PG|PY|PE|PH|PN|PL|PT|PR|QA|RE|RO|RU|RW|BL|SH|KN|LC|MF|PM|VC|WS|SM|ST|SA|SN|RS|SC|SL|SG|SX|SK|SI|SB|SO|ZA|GS|SS|ES|LK|SD|SR|SJ|SZ|SE|CH|SY|TW|TJ|TZ|TH|TL|TG|TK|TO|TT|TN|TR|TM|TC|TV|UG|UA|AE|GB|US|UM|UY|UZ|VU|VE|VN|VG|VI|WF|EH|YE|ZM|ZW|AFG|ALB|DZA|ASM|AND|AGO|AIA|ATA|ATG|ARG|ARM|ABW|AUS|AUT|AZE|BHS|BHR|BGD|BRB|BLR|BEL|BLZ|BEN|BMU|BTN|BOL|BIH|BWA|BVT|BRA|IOT|VGB|BRN|BGR|BFA|BDI|KHM|CMR|CAN|CPV|CYM|CAF|TCD|CHL|CHN|CXR|CCK|COL|COM|COD|COG|COK|CRI|CIV|CUB|CYP|CZE|DNK|DJI|DMA|DOM|ECU|EGY|SLV|GNQ|ERI|EST|ETH|FRO|FLK|FJI|FIN|FRA|GUF|PYF|ATF|GAB|GMB|GEO|DEU|GHA|GIB|GRC|GRL|GRD|GLP|GUM|GTM|GIN|GNB|GUY|HTI|HMD|VAT|HND|HKG|HRV|HUN|ISL|IND|IDN|IRN|IRQ|IRL|ISR|ITA|JAM|JPN|JOR|KAZ|KEN|KIR|PRK|KOR|KWT|KGZ|LAO|LVA|LBN|LSO|LBR|LBY|LIE|LTU|LUX|MAC|MKD|MDG|MWI|MYS|MDV|MLI|MLT|MHL|MTQ|MRT|MUS|MYT|MEX|FSM|MDA|MCO|MNG|MSR|MAR|MOZ|MMR|NAM|NRU|NPL|ANT|NLD|NCL|NZL|NIC|NER|NGA|NIU|NFK|MNP|NOR|OMN|PAK|PLW|PSE|PAN|PNG|PRY|PER|PHL|PCN|POL|PRT|PRI|QAT|REU|ROU|RUS|RWA|SHN|KNA|LCA|SPM|VCT|WSM|SMR|STP|SAU|SEN|SCG|SYC|SLE|SGP|SVK|SVN|SLB|SOM|ZAF|SGS|ESP|LKA|SDN|SUR|SJM|SWZ|SWE|CHE|SYR|TWN|TJK|TZA|THA|TLS|TGO|TKL|TON|TTO|TUN|TUR|TKM|TCA|TUV|VIR|UGA|UKR|ARE|GBR|UMI|USA|URY|UZB|VUT|VEN|VNM|WLF|ESH|YEM|ZMB|ZWE)$" />
		</xs:restriction>
	</xs:simpleType>


	<!-- ? Definición de estructura tipo Salami Slice -->

	<!-- Descendientes de ingredients -->
	<xs:element name="ingredients">
		<xs:complexType>
			<xs:element name="ingredient" type="tipo_texto_varchar">
			<xs:complexType>
				<xs:attribute name="cantidad" type="tipo_integer_positivo" use="required" />
			</xs:complexType>
			<xs:attribute name="comensales" type="xs:integer" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- Descendientes de preparation -->
	<xs:element name="preparation">
		<xs:complexType>
			<xs:element name="step" type="tipo_texto_varchar" />
			<xs:complexType>
				<xs:attribute name="paso" type="tipo_integer_positivo" use="required" />
			</xs:complexType>
			<xs:attribute name="tiempo" type="tipo_tiempo" use="optional" />
		</xs:complexType>
	</xs:element>

	<!-- Descendientes de review-date -->
	<xs:element name="review-date">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="day" type="tipo_dia" />
				<xs:element name="month" type="tipo_mes" />
				<xs:element name="year" type="tipo_anyo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Descendientes de user-review -->
	<xs:element name="user-review">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="review-text" type="tipo_texto_varchar" />
				<xs:element name="review-email" type="tipo_email" />
				<xs:element name="review-points" type="tipo_byte" />
				<xs:element name="review-date" />
			</xs:sequence>
		</xs:complexType>
		<xs:attribute name="usuario" type="tipo_texto_varchar" use="optional" />
	</xs:element>

	<!-- Descendientes de score -->
	<xs:element name="score" maxOccurs="unbounded">
		<xs:complexType>
			<xs:all>
				<xs:element name="user-review" minOccurs="0" maxOccurs="unbounded" />
			</xs:all>
			<xs:attribute name="average_points" type="tipo_byte" />
		</xs:complexType>
	</xs:element>

	<!-- Descendientes de receta -->
	<xs:element name="receta">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre-receta" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="description" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="ingredients" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="preparation" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute type="tipo_dificultad" name="dificultad" use="optional" />
			<xs:attribute type="tipo_texto_varchar" name="picture" use="optional" />
			<xs:attribute type="tipo_texto_varchar" name="author" use="optional" />
			<xs:attribute type="tipo_pais" name="country" use="optional" />
		</xs:complexType>
	</xs:element>

		<!-- Descendientes de recetas -->
		<xs:element name="recetas">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="receta" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>

</xs:schema>

=== JaimeSFC/lenguajes-de-marcas-ejemplos/2 XSD/Tarea 1 - Evaluable/07-recetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<recetas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="07-recetas.xsd">

	<receta dificultad="Media" picture="wp-content/gazpacho.png" author="Martín Berasategui" country="ES">
		<nombre-receta>Gazpacho</nombre-receta>
		<description>La sopa del verano, súper sencilla de preparar y súper refrescante.</description>
		<ingredients comensales="4">
			<ingredient cantidad="1">Ajo</ingredient>
			<ingredient cantidad="1">Pan</ingredient>
			<ingredient cantidad="2">Tomate</ingredient>
			<ingredient cantidad="5">Pepino</ingredient>
		</ingredients>
		<preparation tiempo="00:25">
			<step paso="1">Pelar y cortar bien los vegetales, meter en la turmix con los demás ingredients.</step>
			<step paso="2">Tras 10 nminutos a potencia máxima, añadir 1 litro de agua y enfriar en la nevera.</step>
			<step paso="3">Dejar enfriar durante 20 minutos, pasado ese tiempo, ¡a disfrutar!</step>
		</preparation>
		<score average_points="0">
			<user-review usuario="Loli">
				<review-text>Salio fatal</review-text>
				<review-email>lolin@chupilandia.com</review-email>
				<review-points>0</review-points>
				<review-date>
					<day>13</day>
					<month>Enero</month>
					<year>2022</year>
				</review-date>
			</user-review>
			<user-review usuario="Raul">
				<review-text>Socorro, esto es muy complicado</review-text>
				<review-email>raul@fatal.com</review-email>
				<review-points>0</review-points>
				<review-date>
					<day>20</day>
					<month>Marzo</month>
					<year>2022</year>
				</review-date>
			</user-review>
		</score>
	</receta>

	<receta dificultad="Difícil" picture="wp-content/albondigas.png" author="Arguiñano" country="ES">
		<nombre-receta>Albóndigas</nombre-receta>
		<description>Un manjar de manjares.</description>
		<ingredients comensales="4">
			<ingredient>2 Ajos</ingredient>
			<ingredient>Perejil fresco (un manojo)</ingredient>
			<ingredient>500 gramos de carne picada buena</ingredient>
			<ingredient>2 tomates</ingredient>
			<ingredient>3 cebollas</ingredient>
		</ingredients>
		<preparation tiempo="00:45">
			<step paso="1">Hacer unas bolitas majas con la carne picada.</step>
			<step paso="2">Mezclar todo con cariño y freir en la sarten.</step>
			<step paso="3">Después de 20 minutos freir una patatina y avisar a los niños que está la cena lista</step>
			<step paso="4">¡Rebañar!</step>
		</preparation>
		<score average_points="10">
			<user-review usuario="Chupiman">
				<review-text>Para chuparse los dedos</review-text>
				<review-email>chupiman@chupilandia.com</review-email>
				<review-points>5</review-points>
				<review-date>
					<day>10</day>
					<month>Enero</month>
					<year>2022</year>
				</review-date>
			</user-review>
			<user-review usuario="Felipe">
				<review-text>Puaggg</review-text>
				<review-email>arg@fatal.com</review-email>
				<review-points>0</review-points>
				<review-date>
					<day>20</day>
					<month>Abril</month>
					<year>2022</year>
				</review-date>
			</user-review>
		</score>
	</receta>

	<receta dificultad="Fácil" picture="wp-content/polos.png" author="Anonimo" country="ES">
		<nombre-receta>Polos de hielo</nombre-receta>
		<description>El postre del verano.</description>
		<ingredients comensales="2">
			<ingredient>1 botella de coca cola</ingredient>
		</ingredients>
		<preparation tiempo="00:05">
			<step paso="1">Echar la coca cola en la polera.</step>
			<step paso="2">Meter en el congelador, esperar 30 minutos y a disfrutar.</step>
		</preparation>
	</receta>


</recetas>
