=== JaimeSFC/lenguajes-de-marcas-ejemplos/Tareas-DAM/Tarea 2 - Practicas/06.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" id="paneles">

<!-- Tipo (Restringido a 2 valores) -->
<xs:simpleType name="tipo_restricted">
	<xs:restriction base="xs:string">
<!-- 		<xs:enumeration value="Accidente"/>
		<xs:enumeration value="Retención"/> -->
		<xs:pattern value="Accidente|Retención"/>
	</xs:restriction>
</xs:simpleType>

<!-- Nombre  (Longitud maxima 50) -->
<xs:simpleType name="t_cad50">
	<xs:restriction base="xs:string">
		<xs:maxLength value="50" />
	</xs:restriction>
</xs:simpleType>

<!-- ref  (Patrón) -->
<xs:simpleType name="t_cad_ref">
	<xs:restriction base="xs:string">
<!-- 	<xs:pattern value="[a-zA-Z]{1,3}-[0-9]{1,4}"/> -->
	<xs:pattern value="\w{1,3}-\d{1,4}"/>
	</xs:restriction>
</xs:simpleType>

<!-- origen & destino (Valor minimo / Máximo) -->
<xs:simpleType name="t_cad30">
	<xs:restriction base="xs:string">
		<xs:minLength value="1"/>
		<xs:maxLength value="30" />
	</xs:restriction>
</xs:simpleType>

<!-- doble (Vacío) -->
<xs:simpleType name="t_doble">
	<xs:restriction base="xs:string">
		<xs:maxLength value="0" />
	</xs:restriction>
</xs:simpleType>

<!-- carriles (Valores comprendidos entre ... Incluyendo / Excluyendo -->
<xs:simpleType name="t_entre1y8">
	<xs:restriction base="xs:integer">
<!-- 		<xs:minExclusive value="0" />
		<xs:maxExclusive value="9" /> -->
		<xs:minInclusive value="1" />
		<xs:maxInclusive value="8" />
		<xs:fractionDigits value="0" />
	</xs:restriction>
</xs:simpleType>

<!-- pk (Restrinjo máximo de decimales) -->
<xs:simpleType name="t_3dec">
	<xs:restriction base="xs:decimal">
	<xs:fractionDigits value="3" />
	</xs:restriction>
</xs:simpleType>

<!-- corte -->
<xs:simpleType name="corte">
	<xs:restriction base="xs:string">
		<xs:maxLength value="30" />
	</xs:restriction>
</xs:simpleType>


<!-- sentido (Restringe a 3 valores) -->
<xs:simpleType name="t_1_0">
	<xs:restriction base="xs:string">
<!-- 			<xs:enumeration value="-1"/>
			<xs:enumeration value="0"/>
			<xs:enumeration value="1"/> -->
			<xs:pattern value="-1|0|1"/>
	</xs:restriction>
</xs:simpleType>


<!-- Desc VIA -->
<xs:element name="via">
	<xs:complexType>
		<xs:sequence>
			<xs:element name= "nombre" type="t_cad50" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name= "ref" type="t_cad_ref" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name= "origen" type="t_cad30" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name= "destino" type="t_cad30" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name= "doble" type="t_doble" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name= "carriles" type="t_entre1y8" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!-- Desc Evento -->
<xs:element name="evento">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="via" minOccurs="1"/>
			<xs:element name="pk" type="t_3dec" minOccurs="1"/>
			<xs:element name="retencion" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="long" type="t_3dec" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="corte" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="sentido" type="t_1_0" minOccurs="1"/>
			<xs:element name="carrilescortados">
				<xs:complexType>
					<xs:attribute name="valor" use="required" type="t_entre1y8"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	<xs:attribute name="fecha" use="required" type="xs:date"/>
	<xs:attribute name="tipo" use="required" type="tipo_restricted"/>
	</xs:complexType>
</xs:element>

<!-- Desc paneles -->
<xs:element name="paneles">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="evento" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== JaimeSFC/lenguajes-de-marcas-ejemplos/2 XSD/Tarea 2 - Practicas/06.xml
<?xml version="1.0" encoding="UTF-8"?>
<paneles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="06.xsd">
	<evento tipo="Accidente" fecha="2020-01-01">
		<via>
			<nombre>Autopista del V Centenario</nombre>
			<ref>A-49</ref>
			<origen>Sevilla</origen>
			<destino>Huelva</destino>
			<doble />
			<carriles>1</carriles>
		</via>
		<pk>42.200</pk>
		<retencion long="8.200" />
		<sentido>0</sentido>
		<carrilescortados valor="1" />
	</evento>
	<evento tipo="Retención" fecha="2020-12-02">
		<via>
			<nombre>Autovía de Andalucía</nombre>
			<ref>A-4</ref>
			<origen>Madrid</origen>
			<destino>Cádiz</destino>
			<doble />
			<carriles>4</carriles>
		</via>
		<pk>550.000</pk>
		<retencion long="3.000" />
		<sentido>-1</sentido>
	</evento>
</paneles>
