=== JaimeSFC/lenguajes-de-marcas-ejemplos/unidad6/XSD/Tareas-DAM/Tarea 2 - Evaluable/agendaVersion5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" id="agenda">

<!-- * INICIO componentes alarmaType -->

	<!-- ? Atributos alarmaType  -->
	<xs:simpleType name="t_prioridad">
		<xs:restriction base="xs:string">
			<xs:pattern value="baja|normal|alta" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tono_1a5">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="5" />
			<xs:fractionDigits value="0" />
		</xs:restriction>
	</xs:simpleType>

	<!-- ? Componentes diaType -->
	<xs:simpleType name="t_dia">
		<xs:restriction base="xs:integer">
			<xs:pattern value="(0[1-9]|[12]\d|3[01])" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="t_mes">
		<xs:restriction base="xs:integer">
			<xs:pattern value="(0?[1-9]|1[0-2])" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="t_anyo">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[2022-2199]{4}" />
		</xs:restriction>
	</xs:simpleType>

	<!-- ! Declaro diaType -->
	<xs:complexType name="diaType">
		<xs:sequence>
			<xs:element name="dia" type="t_dia" maxOccurs="unbounded" />
			<xs:element name="mes" type="t_mes" maxOccurs="unbounded" />
			<xs:element name="anyo" type="t_anyo" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

		<!-- ! Descendientes de dia -->
		<xs:complexType name="dia">
			<xs:sequence>
				<xs:element name="diaType" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>

	<!-- ? Componentes de horaType -->
	<xs:simpleType name="t_hora">
		<xs:restriction base="xs:integer">
			<xs:pattern value="([0-1]?[0-9]|2[0-3])" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="t_minuto">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[0-5][0-9]" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="t_segundo">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[00-59]{2}" />
		</xs:restriction>
	</xs:simpleType>

	<!-- ! Declaro horaType -->
	<xs:complexType name="horaType">
		<xs:sequence>
			<xs:element name="hora" type="t_hora" minOccurs="1" maxOccurs="1" />
			<xs:element name="minuto" type="t_minuto" minOccurs="1" maxOccurs="1" />
			<xs:element name="segundo" type="t_segundo" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<!-- ! Descendientes de hora -->
	<xs:complexType name="hora">
		<xs:sequence>
			<xs:element name="horaType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!-- !! Descendientes de diaHora -->
	<xs:element name="diaHora">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="dia" minOccurs="0" maxOccurs="0" />
				<xs:element name="hora" minOccurs="0" maxOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- ? Componentes de alarmaType -->
	<xs:simpleType name="texto_libre_asunto_alarma">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:maxLength value="255" />
		</xs:restriction>
	</xs:simpleType>

	<!-- ! Declaro alarmaType -->
	<xs:complexType name="alarmaType">
		<xs:sequence>
			<xs:element name="asunto" type="texto_libre_asunto_alarma" minOccurs="0" maxOccurs="1" />
			<xs:element name="diaHora" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="prioridad" type="t_prioridad" use="optional" />
		<xs:attribute name="tono" type="tono_1a5" use="required" />
	</xs:complexType>

	<!-- * FIN componentes alarmaType -->

	<!-- !!! Descendientes de alarma -->
	<xs:complexType name="alarma">
		<xs:sequence>
			<xs:element name="alarmaType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!-- !!!! Descendientes de alarmas -->
	<xs:element name="alarmas">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="alarma" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element> 


	<!-- * INICIO componentes correoType -->

	<!-- ? Atributo correoType  -->
	<xs:simpleType name="t_EntradaoSalida">
		<xs:restriction base="xs:string">
			<xs:pattern value="Entrada|Salida" />
		</xs:restriction>
	</xs:simpleType>

	<!-- ? Componentes correoType -->
	<xs:simpleType name="email_address">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{2,64}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="texto_libre_asunto_correo">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:maxLength value="255" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="extension_adjunto">
		<xs:restriction base="xs:string">
			<xs:pattern value=".xml|.xsd|.jpg|.png|.pdf|.pps|.gif" />
		</xs:restriction>
	</xs:simpleType>

	<!-- ! Declaro correoType -->
	<xs:complexType name="correoType">
		<xs:sequence>
			<xs:element name="remitente" type="email_address" minOccurs="1" maxOccurs="1" />
			<xs:element name="destinatario" type="email_address" minOccurs="1" maxOccurs="unbounded" />
			<xs:element name="asunto" type="texto_libre_asunto_correo" minOccurs="0" maxOccurs="1" />
			<xs:element name="adjunto" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType mixed="true">
					<xs:attribute name="extension" type="extension_adjunto" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="EntradaoSalida" type="t_EntradaoSalida" use="required" />
	</xs:complexType>	

	<!-- * FIN componentes correoType -->

	<!-- !!! Descendientes de correo -->
	<xs:complexType name="correo">
		<xs:sequence>
			<xs:element name="correoType" />
		</xs:sequence>
	</xs:complexType>


	<!-- !!!! Descendientes de correos -->
	<xs:element name="correos">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="correo" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>


<!-- * INICIO componentes contactoType -->
		<!-- ? Atributo contactoType  -->
		<xs:simpleType name="t_idioma">
			<xs:restriction base="xs:string">
				<xs:enumeration value="es" />
				<xs:enumeration value="en" />
				<xs:enumeration value="fr" />
			</xs:restriction>
		</xs:simpleType>
	
			<!-- ? Componentes contactoType -->
		<xs:simpleType name="empresaSiNo">
			<xs:restriction base="xs:string">
				<xs:enumeration value="si" />
				<xs:enumeration value="no" />
			</xs:restriction>
		</xs:simpleType>
	
		<xs:simpleType name="t_telefono">
			<xs:restriction base="xs:string">
				<xs:pattern value="\(?\+[0-9]{1,3}\)? ?-?[0-9]{1,3} ?-?[0-9]{3,5} ?-?[0-9]{4}( ?-?[0-9]{3})? ?(\w{1,10}\s?\d{1,6})?" />
			</xs:restriction>
		</xs:simpleType>
	
			<!-- ! Declaro contactoType -->
			<xs:element name="contactoType">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nombre">
							<xs:complexType mixed="true">
								<xs:attribute name="idioma" type="t_idioma" use="required" />
								<xs:attribute name="empresaSiNo" type="empresaSiNo" use="required" />
							</xs:complexType>
						</xs:element>
						<xs:element name="telefono" type="t_telefono" minOccurs="1" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<!-- * FIN componentes contactoType -->
	
				<!-- !!! Descendientes de contacto -->
		<xs:complexType name="contacto">
			<xs:sequence>
				<xs:element name="contactoType" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	
		<!-- !!!! Descendientes de contactos -->
		<xs:element name="contactos">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="contacto" type="t_telefono" minOccurs="1" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	
		<!-- !!!!! Descendientes de agenda -->
		<xs:element name="agenda">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="alarmas" />
					<xs:element name="correos" />
					<xs:element name="contactos" />
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	

	
	</xs:schema>

=== JaimeSFC/lenguajes-de-marcas-ejemplos/unidad6/XSD/Tareas-DAM/Tarea 2 - Evaluable/agendaVersion5.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="agendaVersion5.xsd">

	<alarmas>

		<alarma prioridad="alta" tono="3">
			<diaHora>
				<dia>
					<dia>25</dia>
					<mes>12</mes>
					<anyo>2022</anyo>
				</dia>
				<hora>
					<hora>07</hora>
					<minuto>00</minuto>
					<segundo>00</segundo>
				</hora>
			</diaHora>
			<asunto>A levantarse</asunto>
		</alarma>

		<alarma prioridad="baja" tono="1">
			<diaHora>
				<dia>
					<dia>25</dia>
					<mes>12</mes>
					<anyo>2022</anyo>
				</dia>
				<hora>
					<hora>16</hora>
					<minuto>00</minuto>
					<segundo>00</segundo>
				</hora>
			</diaHora>
			<asunto>Se acabó la siesta</asunto>
		</alarma>

	</alarmas>


	<correos>

		<correo EntradaoSalida="Salida">
			<remitente>jaime@gmail.com</remitente>
			<destinatario>joseluis@educastur.es</destinatario>
			<asunto>Tareas pendientes</asunto>
			<adjunto extension=".xml">agenda.xml</adjunto>
			<adjunto extension=".xsd">agenda.xsd</adjunto>
		</correo>

		<correo EntradaoSalida="Salida">
			<remitente>jaime@gmail.com</remitente>
			<destinatario>felipe@gmail.com</destinatario>
			<destinatario>leticia@gmail.com</destinatario>
			<asunto>Gatitos monísimos</asunto>
			<adjunto extension=".pps">gatitos.pps</adjunto>
		</correo>

		<correo EntradaoSalida="Entrada">
			<remitente>joseluis@educastur.es</remitente>
			<destinatario>jaime@gmail.com</destinatario>
			<asunto>Calificación Jaime</asunto>
			<adjunto extension=".jpg">boletin-notas.jpg</adjunto>

		</correo>


	</correos>

	<contactos>

		<contacto>
			<nombre idioma="en" empresaSiNo="si">Tesla</nombre>
			<telefono>+1273000001</telefono>
		</contacto>

		<contacto>
			<nombre idioma="es" empresaSiNo="si">Jamones de Jabugo</nombre>
			<telefono>+34959128668</telefono>
			<telefono>+34959128669</telefono>

		</contacto>

		<contacto>
			<nombre idioma="fr" empresaSiNo="no">Robespierre</nombre>
			<telefono>+33455638987</telefono>
		</contacto>

	</contactos>

</agenda>
